### ISSUE TITLE
Text field box is not visible

### ISSUE THREAD

**Issue by VishalSpaceO** [sourin00/MaterialChipsInputDemo#3]

**Comment by sourin00** [comment]
> 
Please provide the following info and if possible a screenshot of the issue:

1.Android version
2.Device/Emulator 
3.Any other special cases or interactions that may reproduce the issue.

Thanks.

**Comment by VishalSpaceO** [comment]
Android Version - Android 12
Emulator - Pixel 4 API 3
![Screenshot_1651559859](https://user-images.githubusercontent.com/99634850/166413358-db7da309-ee81-4fe1-a571-6b25720cde09.png)

**Comment by sourin00** [comment]
> Android Version - Android 12 Emulator - Pixel 4 API 3 ![Screenshot_1651559859](https://user-images.githubusercontent.com/99634850/166413358-db7da309-ee81-4fe1-a571-6b25720cde09.png)

This issue is not getting reproduced on Pixel 4 API 31 emulator .. are you using the identical code ? 
you may share your code here in case it's different.

**Comment by VishalSpaceO** [comment]
Yes working fine in API 30.
May be the issue is with the emulator for API 31.
Anyways, Thanks for the Help :+1:
